package semana_03;

import semana_03.Ordenamiento;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class frmMetodos_De_Metodos extends javax.swing.JFrame {

    /**
     * Creates new form frmMetodos_De_Metodos
     */
    public frmMetodos_De_Metodos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla = new javax.swing.JTextArea();
        Mostra_Pantalla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elegir Cantidad Registos:");

        Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "2500", "50000", "100000", "250000", "500000", "750000", "1000000" }));
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });

        Pantalla.setColumns(20);
        Pantalla.setRows(5);
        jScrollPane1.setViewportView(Pantalla);

        Mostra_Pantalla.setText("Iniciar");
        Mostra_Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostra_PantallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Mostra_Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Mostra_Pantalla)
                    .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mostra_PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostra_PantallaActionPerformed
        int numero = Opciones.getSelectedIndex();
        int nCantidadDatos=0;
        switch(numero){
            case 0:
                nCantidadDatos=1000;
                break;
            case 1:
                nCantidadDatos=25000;
                break;
            case 2:
                nCantidadDatos=50000;
                break;
            case 3:
                nCantidadDatos=100000;
                break;
            case 4:
                nCantidadDatos=250000;
                break;
            case 5:
                nCantidadDatos=500000;
                break;
            case 6:
                nCantidadDatos=750000;
                break;
            case 7:
                nCantidadDatos=1000000;
                break;
        }
        int nValorMinimo=0;
        int nValorMaximo=10000;
        int a[]=new int [nCantidadDatos];
        Ordenamiento o=new Ordenamiento ();
        int[] oArreglo = o.DevuelveArreglo(nCantidadDatos, nValorMinimo, nValorMaximo);
        //"Metodo Quickshort"
        long nIniciotiempo= System.currentTimeMillis();
        Ordenamiento.Quickshort(oArreglo, 0, oArreglo.length - 1);            
        long nRetardoTiempo = System.currentTimeMillis() - nIniciotiempo;
        //"Metodo burbuja"
        long nIniciotiempo1= System.currentTimeMillis();
        Ordenamiento.Burbuja(oArreglo);
        long nRetardoTiempo1 = System.currentTimeMillis() - nIniciotiempo1;
        //"Metodo Shell"
        long nIniciotiempo2= System.currentTimeMillis();
        Ordenamiento.Shell(oArreglo);
        long nRetardoTiempo2 = System.currentTimeMillis() - nIniciotiempo2;
        //"Metodo Insercion"
        long nIniciotiempo3= System.currentTimeMillis();
        Ordenamiento.Insercion(oArreglo);
        long nRetardoTiempo3 = System.currentTimeMillis() - nIniciotiempo3;
        Pantalla.setText("Cantidad de Registro:  " + nCantidadDatos  + " \n"
            + " \n"
            + "Metodo                  |"+"     Tiempo de ordenamiento \n" 
            + "------------------------------------------------------------------- \n"
            + "Burbuja                 |                         "+ nRetardoTiempo1+" \n"
            + "Shell                      |                         "+nRetardoTiempo2 + " \n"
            + "Quickshort            |                         "+nRetardoTiempo+ " \n"
            + "Inserccion             |                         "+nRetardoTiempo3 );
        
 // TODO add your handling code here:
    }//GEN-LAST:event_Mostra_PantallaActionPerformed

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMetodos_De_Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMetodos_De_Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMetodos_De_Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMetodos_De_Metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMetodos_De_Metodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostra_Pantalla;
    private javax.swing.JComboBox<String> Opciones;
    private javax.swing.JTextArea Pantalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
